import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Chatroom",
  description: "Generated by Chatroom",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><script src="/bot.js"/></head>
      <body
        className={` antialiased flex flex-col justify-between h-full`}
      >
        
        <Navbar />
        <div className="pt-[10%] md:pt-[3%] w-full z-0 h-[100%]"> {children}</div>
        <div className='items-end'><Footer /></div>
      </body>
    </html>
  );
}
